name: wait-for-workflows-action
description: Wait for workflow runs

inputs:
  initial-delay-seconds:
    description: Initial delay before polling in seconds
    required: true
    default: '10'
  period-seconds:
    description: Polling period in seconds
    required: true
    default: '15'
  filter-workflow-events:
    description: Filter workflows by events (multiline)
    required: false
    default: ${{ github.event_name }}
  exclude-workflow-names:
    description: Exclude specified workflows (multiline)
    required: false
  sha:
    description: Commit SHA to wait for
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  rollup-state:
    description: Either SUCCESS or FAILURE
  failed-workflow-names:
    description: List of failed workflow names (multiline)

runs:
  using: 'node20'
  main: 'dist/index.js'
