name: wait-for-workflows-action
description: Wait for workflow runs

inputs:
  sha:
    description: Commit SHA to wait for
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
