name: wait-for-workflows-action
description: Wait for workflow runs

inputs:
  initial-delay-seconds:
    description: Initial delay before polling in seconds
    required: true
    default: '10'
  period-seconds:
    description: Polling period in seconds
    required: true
    default: '15'
  exclude-workflow-names:
    description: Exclude specified workflows (multiline)
    required: false
  sha:
    description: Commit SHA to wait for
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
