name: wait-for-workflows

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  wait-for-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm build
      - name: Run int128/wait-for-workflows-action
        uses: ./
        with:
          initial-delay-seconds: 0
          period-seconds: 3
          page-size-of-check-suites: 1
          filter-by-current-activity-type: true
